; Automatically generated by gen_levels.go

LEVEL_DATA_LAKE:
istruc level
at level.tt2_filename,	db	"lake.tt2     "
at level.pt0_filename,	db	"lake0.pt     "
at level.pt1_filename,	db	"lake1.pt     "
at level.pt2_filename,	db	"lake2.pt     "
at level.door_tile_ul,	db	16
at level.door_tile_ur,	db	17
at level.door_tile_ll,	db	16
at level.door_tile_lr,	db	17
at level.shp + 0*shp_size + shp.num_distinct_frames,	db	3
at level.shp + 0*shp_size + shp.horizontal,		db	ENEMY_HORIZONTAL_DUPLICATED
at level.shp + 0*shp_size + shp.animation,		db	ENEMY_ANIMATION_ALTERNATE
at level.shp + 0*shp_size + shp.filename,		db	"fb.shp       "
at level.shp + 1*shp_size + shp.num_distinct_frames,	db	3
at level.shp + 1*shp_size + shp.horizontal,		db	ENEMY_HORIZONTAL_DUPLICATED
at level.shp + 1*shp_size + shp.animation,		db	ENEMY_ANIMATION_ALTERNATE
at level.shp + 1*shp_size + shp.filename,		db	"bug.shp      "
at level.shp + 2*shp_size + shp.num_distinct_frames,	db	SHP_UNUSED
at level.shp + 3*shp_size + shp.num_distinct_frames,	db	SHP_UNUSED
; lake0
at level.stages + 0*stage_size + stage.item_type,	db	ITEM_BLASTOLA_COLA
at level.stages + 0*stage_size + stage.item_y,		db	12
at level.stages + 0*stage_size + stage.item_x,		db	112
at level.stages + 0*stage_size + stage.exit_l,		db	1
at level.stages + 0*stage_size + stage.exit_r,		db	EXIT_UNUSED
at level.stages + 0*stage_size + stage.doors + 0*door_size + door.y,		db	10
at level.stages + 0*stage_size + stage.doors + 0*door_size + door.x,		db	118
at level.stages + 0*stage_size + stage.doors + 0*door_size + door.target_level,	db	1
at level.stages + 0*stage_size + stage.doors + 0*door_size + door.target_stage,	db	2
at level.stages + 0*stage_size + stage.doors + 1*door_size + door.y,		db	14
at level.stages + 0*stage_size + stage.doors + 1*door_size + door.x,		db	248
at level.stages + 0*stage_size + stage.doors + 1*door_size + door.target_level,	db	5
at level.stages + 0*stage_size + stage.doors + 1*door_size + door.target_stage,	db	0
at level.stages + 0*stage_size + stage.doors + 2*door_size + door.y,		db	DOOR_UNUSED
at level.stages + 0*stage_size + stage.doors + 2*door_size + door.x,		db	DOOR_UNUSED
at level.stages + 0*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_UNUSED
at level.stages + 0*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_UNUSED
at level.stages + 0*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.shp_index,	db	1
at level.stages + 0*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_LEAP
at level.stages + 0*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.shp_index,	db	1
at level.stages + 0*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_LEAP
; lake1
at level.stages + 1*stage_size + stage.item_type,	db	ITEM_SHIELD
at level.stages + 1*stage_size + stage.item_y,		db	10
at level.stages + 1*stage_size + stage.item_x,		db	178
at level.stages + 1*stage_size + stage.exit_l,		db	2
at level.stages + 1*stage_size + stage.exit_r,		db	0
at level.stages + 1*stage_size + stage.doors + 0*door_size + door.y,		db	DOOR_UNUSED
at level.stages + 1*stage_size + stage.doors + 0*door_size + door.x,		db	DOOR_UNUSED
at level.stages + 1*stage_size + stage.doors + 1*door_size + door.y,		db	DOOR_UNUSED
at level.stages + 1*stage_size + stage.doors + 1*door_size + door.x,		db	DOOR_UNUSED
at level.stages + 1*stage_size + stage.doors + 2*door_size + door.y,		db	DOOR_UNUSED
at level.stages + 1*stage_size + stage.doors + 2*door_size + door.x,		db	DOOR_UNUSED
at level.stages + 1*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 1*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_BOUNCE
at level.stages + 1*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 1*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_BOUNCE
at level.stages + 1*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.shp_index,	db	1
at level.stages + 1*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_LEAP
at level.stages + 1*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.shp_index,	db	1
at level.stages + 1*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_LEAP
; lake2
at level.stages + 2*stage_size + stage.item_type,	db	ITEM_BLASTOLA_COLA
at level.stages + 2*stage_size + stage.item_y,		db	4
at level.stages + 2*stage_size + stage.item_x,		db	124
at level.stages + 2*stage_size + stage.exit_l,		db	EXIT_UNUSED
at level.stages + 2*stage_size + stage.exit_r,		db	1
at level.stages + 2*stage_size + stage.doors + 0*door_size + door.y,		db	14
at level.stages + 2*stage_size + stage.doors + 0*door_size + door.x,		db	10
at level.stages + 2*stage_size + stage.doors + 0*door_size + door.target_level,	db	4
at level.stages + 2*stage_size + stage.doors + 0*door_size + door.target_stage,	db	0
at level.stages + 2*stage_size + stage.doors + 1*door_size + door.y,		db	6
at level.stages + 2*stage_size + stage.doors + 1*door_size + door.x,		db	110
at level.stages + 2*stage_size + stage.doors + 1*door_size + door.target_level,	db	2
at level.stages + 2*stage_size + stage.doors + 1*door_size + door.target_stage,	db	0
at level.stages + 2*stage_size + stage.doors + 2*door_size + door.y,		db	8
at level.stages + 2*stage_size + stage.doors + 2*door_size + door.x,		db	74
at level.stages + 2*stage_size + stage.doors + 2*door_size + door.target_level,	db	3
at level.stages + 2*stage_size + stage.doors + 2*door_size + door.target_stage,	db	1
at level.stages + 2*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 2*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_BOUNCE
at level.stages + 2*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 2*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_BOUNCE
at level.stages + 2*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.shp_index,	db	1
at level.stages + 2*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_LEAP
at level.stages + 2*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.shp_index,	db	1
at level.stages + 2*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_LEAP
iend
resb 208-($-LEVEL_DATA_LAKE)	; padding

LEVEL_DATA_FOREST:
istruc level
at level.tt2_filename,	db	"forest.tt2   "
at level.pt0_filename,	db	"forest0.pt   "
at level.pt1_filename,	db	"forest1.pt   "
at level.pt2_filename,	db	"forest2.pt   "
at level.door_tile_ul,	db	48
at level.door_tile_ur,	db	49
at level.door_tile_ll,	db	48
at level.door_tile_lr,	db	49
at level.shp + 0*shp_size + shp.num_distinct_frames,	db	3
at level.shp + 0*shp_size + shp.horizontal,		db	ENEMY_HORIZONTAL_SEPARATE
at level.shp + 0*shp_size + shp.animation,		db	ENEMY_ANIMATION_ALTERNATE
at level.shp + 0*shp_size + shp.filename,		db	"bird.shp     "
at level.shp + 1*shp_size + shp.num_distinct_frames,	db	3
at level.shp + 1*shp_size + shp.horizontal,		db	ENEMY_HORIZONTAL_SEPARATE
at level.shp + 1*shp_size + shp.animation,		db	ENEMY_ANIMATION_ALTERNATE
at level.shp + 1*shp_size + shp.filename,		db	"bird2.shp    "
at level.shp + 2*shp_size + shp.num_distinct_frames,	db	SHP_UNUSED
at level.shp + 3*shp_size + shp.num_distinct_frames,	db	SHP_UNUSED
; forest0
at level.stages + 0*stage_size + stage.item_type,	db	ITEM_BLASTOLA_COLA
at level.stages + 0*stage_size + stage.item_y,		db	14
at level.stages + 0*stage_size + stage.item_x,		db	12
at level.stages + 0*stage_size + stage.exit_l,		db	EXIT_UNUSED
at level.stages + 0*stage_size + stage.exit_r,		db	1
at level.stages + 0*stage_size + stage.doors + 0*door_size + door.y,		db	12
at level.stages + 0*stage_size + stage.doors + 0*door_size + door.x,		db	12
at level.stages + 0*stage_size + stage.doors + 0*door_size + door.target_level,	db	6
at level.stages + 0*stage_size + stage.doors + 0*door_size + door.target_stage,	db	0
at level.stages + 0*stage_size + stage.doors + 1*door_size + door.y,		db	DOOR_UNUSED
at level.stages + 0*stage_size + stage.doors + 1*door_size + door.x,		db	DOOR_UNUSED
at level.stages + 0*stage_size + stage.doors + 2*door_size + door.y,		db	DOOR_UNUSED
at level.stages + 0*stage_size + stage.doors + 2*door_size + door.x,		db	DOOR_UNUSED
at level.stages + 0*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 0*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_BOUNCE
at level.stages + 0*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 0*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_BOUNCE
at level.stages + 0*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_UNUSED
at level.stages + 0*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_UNUSED
; forest1
at level.stages + 1*stage_size + stage.item_type,	db	ITEM_SHIELD
at level.stages + 1*stage_size + stage.item_y,		db	10
at level.stages + 1*stage_size + stage.item_x,		db	118
at level.stages + 1*stage_size + stage.exit_l,		db	0
at level.stages + 1*stage_size + stage.exit_r,		db	2
at level.stages + 1*stage_size + stage.doors + 0*door_size + door.y,		db	DOOR_UNUSED
at level.stages + 1*stage_size + stage.doors + 0*door_size + door.x,		db	DOOR_UNUSED
at level.stages + 1*stage_size + stage.doors + 1*door_size + door.y,		db	DOOR_UNUSED
at level.stages + 1*stage_size + stage.doors + 1*door_size + door.x,		db	DOOR_UNUSED
at level.stages + 1*stage_size + stage.doors + 2*door_size + door.y,		db	DOOR_UNUSED
at level.stages + 1*stage_size + stage.doors + 2*door_size + door.x,		db	DOOR_UNUSED
at level.stages + 1*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 1*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_BOUNCE
at level.stages + 1*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 1*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_BOUNCE
at level.stages + 1*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_UNUSED
at level.stages + 1*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.shp_index,	db	1
at level.stages + 1*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_SHY
; forest2
at level.stages + 2*stage_size + stage.item_type,	db	ITEM_DOOR_KEY
at level.stages + 2*stage_size + stage.item_y,		db	2
at level.stages + 2*stage_size + stage.item_x,		db	160
at level.stages + 2*stage_size + stage.exit_l,		db	1
at level.stages + 2*stage_size + stage.exit_r,		db	EXIT_UNUSED
at level.stages + 2*stage_size + stage.doors + 0*door_size + door.y,		db	12
at level.stages + 2*stage_size + stage.doors + 0*door_size + door.x,		db	238
at level.stages + 2*stage_size + stage.doors + 0*door_size + door.target_level,	db	0
at level.stages + 2*stage_size + stage.doors + 0*door_size + door.target_stage,	db	0
at level.stages + 2*stage_size + stage.doors + 1*door_size + door.y,		db	14
at level.stages + 2*stage_size + stage.doors + 1*door_size + door.x,		db	160
at level.stages + 2*stage_size + stage.doors + 1*door_size + door.target_level,	db	7
at level.stages + 2*stage_size + stage.doors + 1*door_size + door.target_stage,	db	2
at level.stages + 2*stage_size + stage.doors + 2*door_size + door.y,		db	DOOR_UNUSED
at level.stages + 2*stage_size + stage.doors + 2*door_size + door.x,		db	DOOR_UNUSED
at level.stages + 2*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 2*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_BOUNCE
at level.stages + 2*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.shp_index,	db	1
at level.stages + 2*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_SHY
at level.stages + 2*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 2*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_BOUNCE
at level.stages + 2*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.shp_index,	db	1
at level.stages + 2*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_SHY
iend
resb 208-($-LEVEL_DATA_FOREST)	; padding

LEVEL_DATA_SPACE:
istruc level
at level.tt2_filename,	db	"space.tt2    "
at level.pt0_filename,	db	"space0.pt    "
at level.pt1_filename,	db	"space1.pt    "
at level.pt2_filename,	db	"space2.pt    "
at level.door_tile_ul,	db	51
at level.door_tile_ur,	db	52
at level.door_tile_ll,	db	51
at level.door_tile_lr,	db	52
at level.shp + 0*shp_size + shp.num_distinct_frames,	db	4
at level.shp + 0*shp_size + shp.horizontal,		db	ENEMY_HORIZONTAL_DUPLICATED
at level.shp + 0*shp_size + shp.animation,		db	ENEMY_ANIMATION_LOOP
at level.shp + 0*shp_size + shp.filename,		db	"rock.shp     "
at level.shp + 1*shp_size + shp.num_distinct_frames,	db	4
at level.shp + 1*shp_size + shp.horizontal,		db	ENEMY_HORIZONTAL_DUPLICATED
at level.shp + 1*shp_size + shp.animation,		db	ENEMY_ANIMATION_LOOP
at level.shp + 1*shp_size + shp.filename,		db	"saucer.shp   "
at level.shp + 2*shp_size + shp.num_distinct_frames,	db	SHP_UNUSED
at level.shp + 3*shp_size + shp.num_distinct_frames,	db	SHP_UNUSED
; space0
at level.stages + 0*stage_size + stage.item_type,	db	ITEM_BLASTOLA_COLA
at level.stages + 0*stage_size + stage.item_y,		db	16
at level.stages + 0*stage_size + stage.item_x,		db	10
at level.stages + 0*stage_size + stage.exit_l,		db	EXIT_UNUSED
at level.stages + 0*stage_size + stage.exit_r,		db	1
at level.stages + 0*stage_size + stage.doors + 0*door_size + door.y,		db	12
at level.stages + 0*stage_size + stage.doors + 0*door_size + door.x,		db	2
at level.stages + 0*stage_size + stage.doors + 0*door_size + door.target_level,	db	0
at level.stages + 0*stage_size + stage.doors + 0*door_size + door.target_stage,	db	2
at level.stages + 0*stage_size + stage.doors + 1*door_size + door.y,		db	DOOR_UNUSED
at level.stages + 0*stage_size + stage.doors + 1*door_size + door.x,		db	DOOR_UNUSED
at level.stages + 0*stage_size + stage.doors + 2*door_size + door.y,		db	DOOR_UNUSED
at level.stages + 0*stage_size + stage.doors + 2*door_size + door.x,		db	DOOR_UNUSED
at level.stages + 0*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 0*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_BOUNCE
at level.stages + 0*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 0*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_BOUNCE
at level.stages + 0*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 0*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_BOUNCE
at level.stages + 0*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 0*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_BOUNCE
; space1
at level.stages + 1*stage_size + stage.item_type,	db	ITEM_SHIELD
at level.stages + 1*stage_size + stage.item_y,		db	8
at level.stages + 1*stage_size + stage.item_x,		db	114
at level.stages + 1*stage_size + stage.exit_l,		db	0
at level.stages + 1*stage_size + stage.exit_r,		db	2
at level.stages + 1*stage_size + stage.doors + 0*door_size + door.y,		db	DOOR_UNUSED
at level.stages + 1*stage_size + stage.doors + 0*door_size + door.x,		db	DOOR_UNUSED
at level.stages + 1*stage_size + stage.doors + 1*door_size + door.y,		db	DOOR_UNUSED
at level.stages + 1*stage_size + stage.doors + 1*door_size + door.x,		db	DOOR_UNUSED
at level.stages + 1*stage_size + stage.doors + 2*door_size + door.y,		db	DOOR_UNUSED
at level.stages + 1*stage_size + stage.doors + 2*door_size + door.x,		db	DOOR_UNUSED
at level.stages + 1*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 1*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_BOUNCE
at level.stages + 1*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 1*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_BOUNCE
at level.stages + 1*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 1*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_BOUNCE
at level.stages + 1*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.shp_index,	db	1
at level.stages + 1*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_BOUNCE
; space2
at level.stages + 2*stage_size + stage.item_type,	db	ITEM_GEMS
at level.stages + 2*stage_size + stage.item_y,		db	6
at level.stages + 2*stage_size + stage.item_x,		db	198
at level.stages + 2*stage_size + stage.exit_l,		db	1
at level.stages + 2*stage_size + stage.exit_r,		db	EXIT_UNUSED
at level.stages + 2*stage_size + stage.doors + 0*door_size + door.y,		db	12
at level.stages + 2*stage_size + stage.doors + 0*door_size + door.x,		db	228
at level.stages + 2*stage_size + stage.doors + 0*door_size + door.target_level,	db	3
at level.stages + 2*stage_size + stage.doors + 0*door_size + door.target_stage,	db	0
at level.stages + 2*stage_size + stage.doors + 1*door_size + door.y,		db	DOOR_UNUSED
at level.stages + 2*stage_size + stage.doors + 1*door_size + door.x,		db	DOOR_UNUSED
at level.stages + 2*stage_size + stage.doors + 2*door_size + door.y,		db	DOOR_UNUSED
at level.stages + 2*stage_size + stage.doors + 2*door_size + door.x,		db	DOOR_UNUSED
at level.stages + 2*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 2*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_BOUNCE
at level.stages + 2*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 2*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_BOUNCE
at level.stages + 2*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.shp_index,	db	1
at level.stages + 2*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_BOUNCE
at level.stages + 2*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.shp_index,	db	1
at level.stages + 2*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_BOUNCE | ENEMY_BEHAVIOR_FAST
iend
resb 208-($-LEVEL_DATA_SPACE)	; padding

LEVEL_DATA_BASE:
istruc level
at level.tt2_filename,	db	"base.tt2     "
at level.pt0_filename,	db	"base0.pt     "
at level.pt1_filename,	db	"base1.pt     "
at level.pt2_filename,	db	"base2.pt     "
at level.door_tile_ul,	db	9
at level.door_tile_ur,	db	10
at level.door_tile_ll,	db	11
at level.door_tile_lr,	db	12
at level.shp + 0*shp_size + shp.num_distinct_frames,	db	3
at level.shp + 0*shp_size + shp.horizontal,		db	ENEMY_HORIZONTAL_DUPLICATED
at level.shp + 0*shp_size + shp.animation,		db	ENEMY_ANIMATION_ALTERNATE
at level.shp + 0*shp_size + shp.filename,		db	"bug.shp      "
at level.shp + 1*shp_size + shp.num_distinct_frames,	db	4
at level.shp + 1*shp_size + shp.horizontal,		db	ENEMY_HORIZONTAL_DUPLICATED
at level.shp + 1*shp_size + shp.animation,		db	ENEMY_ANIMATION_LOOP
at level.shp + 1*shp_size + shp.filename,		db	"globe.shp    "
at level.shp + 2*shp_size + shp.num_distinct_frames,	db	SHP_UNUSED
at level.shp + 3*shp_size + shp.num_distinct_frames,	db	SHP_UNUSED
; base0
at level.stages + 0*stage_size + stage.item_type,	db	ITEM_SHIELD
at level.stages + 0*stage_size + stage.item_y,		db	4
at level.stages + 0*stage_size + stage.item_x,		db	252
at level.stages + 0*stage_size + stage.exit_l,		db	1
at level.stages + 0*stage_size + stage.exit_r,		db	2
at level.stages + 0*stage_size + stage.doors + 0*door_size + door.y,		db	14
at level.stages + 0*stage_size + stage.doors + 0*door_size + door.x,		db	240
at level.stages + 0*stage_size + stage.doors + 0*door_size + door.target_level,	db	3
at level.stages + 0*stage_size + stage.doors + 0*door_size + door.target_stage,	db	2
at level.stages + 0*stage_size + stage.doors + 1*door_size + door.y,		db	14
at level.stages + 0*stage_size + stage.doors + 1*door_size + door.x,		db	114
at level.stages + 0*stage_size + stage.doors + 1*door_size + door.target_level,	db	3
at level.stages + 0*stage_size + stage.doors + 1*door_size + door.target_stage,	db	1
at level.stages + 0*stage_size + stage.doors + 2*door_size + door.y,		db	8
at level.stages + 0*stage_size + stage.doors + 2*door_size + door.x,		db	138
at level.stages + 0*stage_size + stage.doors + 2*door_size + door.target_level,	db	2
at level.stages + 0*stage_size + stage.doors + 2*door_size + door.target_stage,	db	2
at level.stages + 0*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 0*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_LEAP
at level.stages + 0*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 0*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_LEAP
at level.stages + 0*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 0*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_LEAP
at level.stages + 0*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.shp_index,	db	1
at level.stages + 0*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_ROLL
; base1
at level.stages + 1*stage_size + stage.item_type,	db	ITEM_CORKSCREW
at level.stages + 1*stage_size + stage.item_y,		db	16
at level.stages + 1*stage_size + stage.item_x,		db	0
at level.stages + 1*stage_size + stage.exit_l,		db	EXIT_UNUSED
at level.stages + 1*stage_size + stage.exit_r,		db	0
at level.stages + 1*stage_size + stage.doors + 0*door_size + door.y,		db	6
at level.stages + 1*stage_size + stage.doors + 0*door_size + door.x,		db	0
at level.stages + 1*stage_size + stage.doors + 0*door_size + door.target_level,	db	0
at level.stages + 1*stage_size + stage.doors + 0*door_size + door.target_stage,	db	2
at level.stages + 1*stage_size + stage.doors + 1*door_size + door.y,		db	14
at level.stages + 1*stage_size + stage.doors + 1*door_size + door.x,		db	112
at level.stages + 1*stage_size + stage.doors + 1*door_size + door.target_level,	db	3
at level.stages + 1*stage_size + stage.doors + 1*door_size + door.target_stage,	db	0
at level.stages + 1*stage_size + stage.doors + 2*door_size + door.y,		db	0
at level.stages + 1*stage_size + stage.doors + 2*door_size + door.x,		db	0
at level.stages + 1*stage_size + stage.doors + 2*door_size + door.target_level,	db	3
at level.stages + 1*stage_size + stage.doors + 2*door_size + door.target_stage,	db	2
at level.stages + 1*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 1*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_LEAP
at level.stages + 1*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 1*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_LEAP
at level.stages + 1*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 1*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_LEAP
at level.stages + 1*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.shp_index,	db	1
at level.stages + 1*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_ROLL
; base2
at level.stages + 2*stage_size + stage.item_type,	db	ITEM_BOOTS
at level.stages + 2*stage_size + stage.item_y,		db	16
at level.stages + 2*stage_size + stage.item_x,		db	230
at level.stages + 2*stage_size + stage.exit_l,		db	0
at level.stages + 2*stage_size + stage.exit_r,		db	EXIT_UNUSED
at level.stages + 2*stage_size + stage.doors + 0*door_size + door.y,		db	2
at level.stages + 2*stage_size + stage.doors + 0*door_size + door.x,		db	36
at level.stages + 2*stage_size + stage.doors + 0*door_size + door.target_level,	db	3
at level.stages + 2*stage_size + stage.doors + 0*door_size + door.target_stage,	db	0
at level.stages + 2*stage_size + stage.doors + 1*door_size + door.y,		db	14
at level.stages + 2*stage_size + stage.doors + 1*door_size + door.x,		db	218
at level.stages + 2*stage_size + stage.doors + 1*door_size + door.target_level,	db	3
at level.stages + 2*stage_size + stage.doors + 1*door_size + door.target_stage,	db	1
at level.stages + 2*stage_size + stage.doors + 2*door_size + door.y,		db	DOOR_UNUSED
at level.stages + 2*stage_size + stage.doors + 2*door_size + door.x,		db	DOOR_UNUSED
at level.stages + 2*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 2*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_LEAP
at level.stages + 2*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 2*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_LEAP
at level.stages + 2*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.shp_index,	db	1
at level.stages + 2*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_ROLL
at level.stages + 2*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.shp_index,	db	1
at level.stages + 2*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_ROLL | ENEMY_BEHAVIOR_FAST
iend
resb 208-($-LEVEL_DATA_BASE)	; padding

LEVEL_DATA_CAVE:
istruc level
at level.tt2_filename,	db	"cave.tt2     "
at level.pt0_filename,	db	"cave0.pt     "
at level.pt1_filename,	db	"cave1.pt     "
at level.pt2_filename,	db	"cave2.pt     "
at level.door_tile_ul,	db	5
at level.door_tile_ur,	db	5
at level.door_tile_ll,	db	5
at level.door_tile_lr,	db	5
at level.shp + 0*shp_size + shp.num_distinct_frames,	db	3
at level.shp + 0*shp_size + shp.horizontal,		db	ENEMY_HORIZONTAL_DUPLICATED
at level.shp + 0*shp_size + shp.animation,		db	ENEMY_ANIMATION_ALTERNATE
at level.shp + 0*shp_size + shp.filename,		db	"frog.shp     "
at level.shp + 1*shp_size + shp.num_distinct_frames,	db	3
at level.shp + 1*shp_size + shp.horizontal,		db	ENEMY_HORIZONTAL_SEPARATE
at level.shp + 1*shp_size + shp.animation,		db	ENEMY_ANIMATION_ALTERNATE
at level.shp + 1*shp_size + shp.filename,		db	"bee.shp      "
at level.shp + 2*shp_size + shp.num_distinct_frames,	db	SHP_UNUSED
at level.shp + 3*shp_size + shp.num_distinct_frames,	db	SHP_UNUSED
; cave0
at level.stages + 0*stage_size + stage.item_type,	db	ITEM_SHIELD
at level.stages + 0*stage_size + stage.item_y,		db	6
at level.stages + 0*stage_size + stage.item_x,		db	41
at level.stages + 0*stage_size + stage.exit_l,		db	EXIT_UNUSED
at level.stages + 0*stage_size + stage.exit_r,		db	1
at level.stages + 0*stage_size + stage.doors + 0*door_size + door.y,		db	12
at level.stages + 0*stage_size + stage.doors + 0*door_size + door.x,		db	8
at level.stages + 0*stage_size + stage.doors + 0*door_size + door.target_level,	db	0
at level.stages + 0*stage_size + stage.doors + 0*door_size + door.target_stage,	db	2
at level.stages + 0*stage_size + stage.doors + 1*door_size + door.y,		db	4
at level.stages + 0*stage_size + stage.doors + 1*door_size + door.x,		db	40
at level.stages + 0*stage_size + stage.doors + 1*door_size + door.target_level,	db	4
at level.stages + 0*stage_size + stage.doors + 1*door_size + door.target_stage,	db	1
at level.stages + 0*stage_size + stage.doors + 2*door_size + door.y,		db	2
at level.stages + 0*stage_size + stage.doors + 2*door_size + door.x,		db	154
at level.stages + 0*stage_size + stage.doors + 2*door_size + door.target_level,	db	4
at level.stages + 0*stage_size + stage.doors + 2*door_size + door.target_stage,	db	2
at level.stages + 0*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 0*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_LEAP
at level.stages + 0*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 0*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_LEAP
at level.stages + 0*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 0*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_LEAP | ENEMY_BEHAVIOR_FAST
at level.stages + 0*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.shp_index,	db	1
at level.stages + 0*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_SEEK
; cave1
at level.stages + 1*stage_size + stage.item_type,	db	ITEM_GOLD
at level.stages + 1*stage_size + stage.item_y,		db	4
at level.stages + 1*stage_size + stage.item_x,		db	228
at level.stages + 1*stage_size + stage.exit_l,		db	0
at level.stages + 1*stage_size + stage.exit_r,		db	2
at level.stages + 1*stage_size + stage.doors + 0*door_size + door.y,		db	14
at level.stages + 1*stage_size + stage.doors + 0*door_size + door.x,		db	236
at level.stages + 1*stage_size + stage.doors + 0*door_size + door.target_level,	db	4
at level.stages + 1*stage_size + stage.doors + 0*door_size + door.target_stage,	db	0
at level.stages + 1*stage_size + stage.doors + 1*door_size + door.y,		db	DOOR_UNUSED
at level.stages + 1*stage_size + stage.doors + 1*door_size + door.x,		db	DOOR_UNUSED
at level.stages + 1*stage_size + stage.doors + 2*door_size + door.y,		db	DOOR_UNUSED
at level.stages + 1*stage_size + stage.doors + 2*door_size + door.x,		db	DOOR_UNUSED
at level.stages + 1*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 1*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_LEAP
at level.stages + 1*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 1*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_LEAP | ENEMY_BEHAVIOR_FAST
at level.stages + 1*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.shp_index,	db	1
at level.stages + 1*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_SEEK
at level.stages + 1*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.shp_index,	db	1
at level.stages + 1*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_SEEK
; cave2
at level.stages + 2*stage_size + stage.item_type,	db	ITEM_TELEPORT_WAND
at level.stages + 2*stage_size + stage.item_y,		db	10
at level.stages + 2*stage_size + stage.item_x,		db	64
at level.stages + 2*stage_size + stage.exit_l,		db	1
at level.stages + 2*stage_size + stage.exit_r,		db	EXIT_UNUSED
at level.stages + 2*stage_size + stage.doors + 0*door_size + door.y,		db	14
at level.stages + 2*stage_size + stage.doors + 0*door_size + door.x,		db	236
at level.stages + 2*stage_size + stage.doors + 0*door_size + door.target_level,	db	4
at level.stages + 2*stage_size + stage.doors + 0*door_size + door.target_stage,	db	0
at level.stages + 2*stage_size + stage.doors + 1*door_size + door.y,		db	DOOR_UNUSED
at level.stages + 2*stage_size + stage.doors + 1*door_size + door.x,		db	DOOR_UNUSED
at level.stages + 2*stage_size + stage.doors + 2*door_size + door.y,		db	DOOR_UNUSED
at level.stages + 2*stage_size + stage.doors + 2*door_size + door.x,		db	DOOR_UNUSED
at level.stages + 2*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 2*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_LEAP
at level.stages + 2*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 2*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_LEAP | ENEMY_BEHAVIOR_FAST
at level.stages + 2*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.shp_index,	db	1
at level.stages + 2*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_SEEK
at level.stages + 2*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.shp_index,	db	1
at level.stages + 2*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_SEEK
iend
resb 208-($-LEVEL_DATA_CAVE)	; padding

LEVEL_DATA_SHED:
istruc level
at level.tt2_filename,	db	"shed.tt2     "
at level.pt0_filename,	db	"shed0.pt     "
at level.pt1_filename,	db	"shed1.pt     "
at level.pt2_filename,	db	"shed2.pt     "
at level.door_tile_ul,	db	10
at level.door_tile_ur,	db	11
at level.door_tile_ll,	db	10
at level.door_tile_lr,	db	11
at level.shp + 0*shp_size + shp.num_distinct_frames,	db	3
at level.shp + 0*shp_size + shp.horizontal,		db	ENEMY_HORIZONTAL_SEPARATE
at level.shp + 0*shp_size + shp.animation,		db	ENEMY_ANIMATION_ALTERNATE
at level.shp + 0*shp_size + shp.filename,		db	"bird.shp     "
at level.shp + 1*shp_size + shp.num_distinct_frames,	db	3
at level.shp + 1*shp_size + shp.horizontal,		db	ENEMY_HORIZONTAL_SEPARATE
at level.shp + 1*shp_size + shp.animation,		db	ENEMY_ANIMATION_ALTERNATE
at level.shp + 1*shp_size + shp.filename,		db	"bee.shp      "
at level.shp + 2*shp_size + shp.num_distinct_frames,	db	4
at level.shp + 2*shp_size + shp.horizontal,		db	ENEMY_HORIZONTAL_DUPLICATED
at level.shp + 2*shp_size + shp.animation,		db	ENEMY_ANIMATION_LOOP
at level.shp + 2*shp_size + shp.filename,		db	"ball.shp     "
at level.shp + 3*shp_size + shp.num_distinct_frames,	db	SHP_UNUSED
; shed0
at level.stages + 0*stage_size + stage.item_type,	db	ITEM_SHIELD
at level.stages + 0*stage_size + stage.item_y,		db	12
at level.stages + 0*stage_size + stage.item_x,		db	162
at level.stages + 0*stage_size + stage.exit_l,		db	EXIT_UNUSED
at level.stages + 0*stage_size + stage.exit_r,		db	1
at level.stages + 0*stage_size + stage.doors + 0*door_size + door.y,		db	12
at level.stages + 0*stage_size + stage.doors + 0*door_size + door.x,		db	4
at level.stages + 0*stage_size + stage.doors + 0*door_size + door.target_level,	db	0
at level.stages + 0*stage_size + stage.doors + 0*door_size + door.target_stage,	db	0
at level.stages + 0*stage_size + stage.doors + 1*door_size + door.y,		db	DOOR_UNUSED
at level.stages + 0*stage_size + stage.doors + 1*door_size + door.x,		db	DOOR_UNUSED
at level.stages + 0*stage_size + stage.doors + 2*door_size + door.y,		db	DOOR_UNUSED
at level.stages + 0*stage_size + stage.doors + 2*door_size + door.x,		db	DOOR_UNUSED
at level.stages + 0*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 0*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_BOUNCE
at level.stages + 0*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 0*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_BOUNCE
at level.stages + 0*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.shp_index,	db	1
at level.stages + 0*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_SEEK
at level.stages + 0*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.shp_index,	db	2
at level.stages + 0*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_LEAP
; shed1
at level.stages + 1*stage_size + stage.item_type,	db	ITEM_BLASTOLA_COLA
at level.stages + 1*stage_size + stage.item_y,		db	4
at level.stages + 1*stage_size + stage.item_x,		db	250
at level.stages + 1*stage_size + stage.exit_l,		db	0
at level.stages + 1*stage_size + stage.exit_r,		db	EXIT_UNUSED
at level.stages + 1*stage_size + stage.doors + 0*door_size + door.y,		db	4
at level.stages + 1*stage_size + stage.doors + 0*door_size + door.x,		db	240
at level.stages + 1*stage_size + stage.doors + 0*door_size + door.target_level,	db	5
at level.stages + 1*stage_size + stage.doors + 0*door_size + door.target_stage,	db	2
at level.stages + 1*stage_size + stage.doors + 1*door_size + door.y,		db	DOOR_UNUSED
at level.stages + 1*stage_size + stage.doors + 1*door_size + door.x,		db	DOOR_UNUSED
at level.stages + 1*stage_size + stage.doors + 2*door_size + door.y,		db	DOOR_UNUSED
at level.stages + 1*stage_size + stage.doors + 2*door_size + door.x,		db	DOOR_UNUSED
at level.stages + 1*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 1*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_BOUNCE
at level.stages + 1*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.shp_index,	db	1
at level.stages + 1*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_SEEK
at level.stages + 1*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.shp_index,	db	2
at level.stages + 1*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_LEAP
at level.stages + 1*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.shp_index,	db	2
at level.stages + 1*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_LEAP
; shed2
at level.stages + 2*stage_size + stage.item_type,	db	ITEM_SHIELD
at level.stages + 2*stage_size + stage.item_y,		db	10
at level.stages + 2*stage_size + stage.item_x,		db	246
at level.stages + 2*stage_size + stage.exit_l,		db	EXIT_UNUSED
at level.stages + 2*stage_size + stage.exit_r,		db	EXIT_UNUSED
at level.stages + 2*stage_size + stage.doors + 0*door_size + door.y,		db	14
at level.stages + 2*stage_size + stage.doors + 0*door_size + door.x,		db	4
at level.stages + 2*stage_size + stage.doors + 0*door_size + door.target_level,	db	5
at level.stages + 2*stage_size + stage.doors + 0*door_size + door.target_stage,	db	1
at level.stages + 2*stage_size + stage.doors + 1*door_size + door.y,		db	8
at level.stages + 2*stage_size + stage.doors + 1*door_size + door.x,		db	242
at level.stages + 2*stage_size + stage.doors + 1*door_size + door.target_level,	db	7
at level.stages + 2*stage_size + stage.doors + 1*door_size + door.target_stage,	db	0
at level.stages + 2*stage_size + stage.doors + 2*door_size + door.y,		db	DOOR_UNUSED
at level.stages + 2*stage_size + stage.doors + 2*door_size + door.x,		db	DOOR_UNUSED
at level.stages + 2*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 2*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_BOUNCE | ENEMY_BEHAVIOR_FAST
at level.stages + 2*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.shp_index,	db	1
at level.stages + 2*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_SEEK
at level.stages + 2*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.shp_index,	db	2
at level.stages + 2*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_LEAP
at level.stages + 2*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.shp_index,	db	2
at level.stages + 2*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_LEAP | ENEMY_BEHAVIOR_FAST
iend
resb 208-($-LEVEL_DATA_SHED)	; padding

LEVEL_DATA_CASTLE:
istruc level
at level.tt2_filename,	db	"castle.tt2   "
at level.pt0_filename,	db	"castle0.pt   "
at level.pt1_filename,	db	"castle1.pt   "
at level.pt2_filename,	db	"castle2.pt   "
at level.door_tile_ul,	db	26
at level.door_tile_ur,	db	27
at level.door_tile_ll,	db	26
at level.door_tile_lr,	db	27
at level.shp + 0*shp_size + shp.num_distinct_frames,	db	3
at level.shp + 0*shp_size + shp.horizontal,		db	ENEMY_HORIZONTAL_SEPARATE
at level.shp + 0*shp_size + shp.animation,		db	ENEMY_ANIMATION_ALTERNATE
at level.shp + 0*shp_size + shp.filename,		db	"bird.shp     "
at level.shp + 1*shp_size + shp.num_distinct_frames,	db	4
at level.shp + 1*shp_size + shp.horizontal,		db	ENEMY_HORIZONTAL_DUPLICATED
at level.shp + 1*shp_size + shp.animation,		db	ENEMY_ANIMATION_LOOP
at level.shp + 1*shp_size + shp.filename,		db	"ball.shp     "
at level.shp + 2*shp_size + shp.num_distinct_frames,	db	4
at level.shp + 2*shp_size + shp.horizontal,		db	ENEMY_HORIZONTAL_DUPLICATED
at level.shp + 2*shp_size + shp.animation,		db	ENEMY_ANIMATION_LOOP
at level.shp + 2*shp_size + shp.filename,		db	"cube.shp     "
at level.shp + 3*shp_size + shp.num_distinct_frames,	db	3
at level.shp + 3*shp_size + shp.horizontal,		db	ENEMY_HORIZONTAL_SEPARATE
at level.shp + 3*shp_size + shp.animation,		db	ENEMY_ANIMATION_ALTERNATE
at level.shp + 3*shp_size + shp.filename,		db	"bee.shp      "
; castle0
at level.stages + 0*stage_size + stage.item_type,	db	ITEM_CROWN
at level.stages + 0*stage_size + stage.item_y,		db	2
at level.stages + 0*stage_size + stage.item_x,		db	244
at level.stages + 0*stage_size + stage.exit_l,		db	EXIT_UNUSED
at level.stages + 0*stage_size + stage.exit_r,		db	EXIT_UNUSED
at level.stages + 0*stage_size + stage.doors + 0*door_size + door.y,		db	14
at level.stages + 0*stage_size + stage.doors + 0*door_size + door.x,		db	246
at level.stages + 0*stage_size + stage.doors + 0*door_size + door.target_level,	db	1
at level.stages + 0*stage_size + stage.doors + 0*door_size + door.target_stage,	db	0
at level.stages + 0*stage_size + stage.doors + 1*door_size + door.y,		db	4
at level.stages + 0*stage_size + stage.doors + 1*door_size + door.x,		db	228
at level.stages + 0*stage_size + stage.doors + 1*door_size + door.target_level,	db	6
at level.stages + 0*stage_size + stage.doors + 1*door_size + door.target_stage,	db	2
at level.stages + 0*stage_size + stage.doors + 2*door_size + door.y,		db	8
at level.stages + 0*stage_size + stage.doors + 2*door_size + door.x,		db	8
at level.stages + 0*stage_size + stage.doors + 2*door_size + door.target_level,	db	6
at level.stages + 0*stage_size + stage.doors + 2*door_size + door.target_stage,	db	1
at level.stages + 0*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 0*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_BOUNCE | ENEMY_BEHAVIOR_FAST
at level.stages + 0*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.shp_index,	db	1
at level.stages + 0*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_LEAP
at level.stages + 0*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.shp_index,	db	1
at level.stages + 0*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_LEAP | ENEMY_BEHAVIOR_FAST
at level.stages + 0*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.shp_index,	db	3
at level.stages + 0*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_SEEK
; castle1
at level.stages + 1*stage_size + stage.item_type,	db	ITEM_SHIELD
at level.stages + 1*stage_size + stage.item_y,		db	14
at level.stages + 1*stage_size + stage.item_x,		db	66
at level.stages + 1*stage_size + stage.exit_l,		db	EXIT_UNUSED
at level.stages + 1*stage_size + stage.exit_r,		db	EXIT_UNUSED
at level.stages + 1*stage_size + stage.doors + 0*door_size + door.y,		db	14
at level.stages + 1*stage_size + stage.doors + 0*door_size + door.x,		db	8
at level.stages + 1*stage_size + stage.doors + 0*door_size + door.target_level,	db	6
at level.stages + 1*stage_size + stage.doors + 0*door_size + door.target_stage,	db	0
at level.stages + 1*stage_size + stage.doors + 1*door_size + door.y,		db	2
at level.stages + 1*stage_size + stage.doors + 1*door_size + door.x,		db	8
at level.stages + 1*stage_size + stage.doors + 1*door_size + door.target_level,	db	6
at level.stages + 1*stage_size + stage.doors + 1*door_size + door.target_stage,	db	2
at level.stages + 1*stage_size + stage.doors + 2*door_size + door.y,		db	DOOR_UNUSED
at level.stages + 1*stage_size + stage.doors + 2*door_size + door.x,		db	DOOR_UNUSED
at level.stages + 1*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 1*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_BOUNCE | ENEMY_BEHAVIOR_FAST
at level.stages + 1*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.shp_index,	db	1
at level.stages + 1*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_LEAP
at level.stages + 1*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.shp_index,	db	1
at level.stages + 1*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_LEAP | ENEMY_BEHAVIOR_FAST
at level.stages + 1*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.shp_index,	db	2
at level.stages + 1*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_SHY
; castle2
at level.stages + 2*stage_size + stage.item_type,	db	ITEM_SHIELD
at level.stages + 2*stage_size + stage.item_y,		db	8
at level.stages + 2*stage_size + stage.item_x,		db	44
at level.stages + 2*stage_size + stage.exit_l,		db	EXIT_UNUSED
at level.stages + 2*stage_size + stage.exit_r,		db	EXIT_UNUSED
at level.stages + 2*stage_size + stage.doors + 0*door_size + door.y,		db	8
at level.stages + 2*stage_size + stage.doors + 0*door_size + door.x,		db	8
at level.stages + 2*stage_size + stage.doors + 0*door_size + door.target_level,	db	6
at level.stages + 2*stage_size + stage.doors + 0*door_size + door.target_stage,	db	1
at level.stages + 2*stage_size + stage.doors + 1*door_size + door.y,		db	4
at level.stages + 2*stage_size + stage.doors + 1*door_size + door.x,		db	246
at level.stages + 2*stage_size + stage.doors + 1*door_size + door.target_level,	db	6
at level.stages + 2*stage_size + stage.doors + 1*door_size + door.target_stage,	db	0
at level.stages + 2*stage_size + stage.doors + 2*door_size + door.y,		db	DOOR_UNUSED
at level.stages + 2*stage_size + stage.doors + 2*door_size + door.x,		db	DOOR_UNUSED
at level.stages + 2*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.shp_index,	db	1
at level.stages + 2*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_LEAP
at level.stages + 2*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.shp_index,	db	2
at level.stages + 2*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_SHY | ENEMY_BEHAVIOR_FAST
at level.stages + 2*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.shp_index,	db	3
at level.stages + 2*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_SEEK
at level.stages + 2*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.shp_index,	db	3
at level.stages + 2*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_SEEK | ENEMY_BEHAVIOR_FAST
iend
resb 208-($-LEVEL_DATA_CASTLE)	; padding

LEVEL_DATA_COMP:
istruc level
at level.tt2_filename,	db	"comp.tt2     "
at level.pt0_filename,	db	"comp0.pt     "
at level.pt1_filename,	db	"comp1.pt     "
at level.pt2_filename,	db	"comp2.pt     "
at level.door_tile_ul,	db	2
at level.door_tile_ur,	db	3
at level.door_tile_ll,	db	4
at level.door_tile_lr,	db	5
at level.shp + 0*shp_size + shp.num_distinct_frames,	db	4
at level.shp + 0*shp_size + shp.horizontal,		db	ENEMY_HORIZONTAL_DUPLICATED
at level.shp + 0*shp_size + shp.animation,		db	ENEMY_ANIMATION_LOOP
at level.shp + 0*shp_size + shp.filename,		db	"star1.shp    "
at level.shp + 1*shp_size + shp.num_distinct_frames,	db	4
at level.shp + 1*shp_size + shp.horizontal,		db	ENEMY_HORIZONTAL_DUPLICATED
at level.shp + 1*shp_size + shp.animation,		db	ENEMY_ANIMATION_LOOP
at level.shp + 1*shp_size + shp.filename,		db	"star2.shp    "
at level.shp + 2*shp_size + shp.num_distinct_frames,	db	3
at level.shp + 2*shp_size + shp.horizontal,		db	ENEMY_HORIZONTAL_DUPLICATED
at level.shp + 2*shp_size + shp.animation,		db	ENEMY_ANIMATION_ALTERNATE
at level.shp + 2*shp_size + shp.filename,		db	"star3.shp    "
at level.shp + 3*shp_size + shp.num_distinct_frames,	db	SHP_UNUSED
; comp0
at level.stages + 0*stage_size + stage.item_type,	db	ITEM_SHIELD
at level.stages + 0*stage_size + stage.item_y,		db	2
at level.stages + 0*stage_size + stage.item_x,		db	140
at level.stages + 0*stage_size + stage.exit_l,		db	EXIT_UNUSED
at level.stages + 0*stage_size + stage.exit_r,		db	1
at level.stages + 0*stage_size + stage.doors + 0*door_size + door.y,		db	8
at level.stages + 0*stage_size + stage.doors + 0*door_size + door.x,		db	6
at level.stages + 0*stage_size + stage.doors + 0*door_size + door.target_level,	db	5
at level.stages + 0*stage_size + stage.doors + 0*door_size + door.target_stage,	db	2
at level.stages + 0*stage_size + stage.doors + 1*door_size + door.y,		db	DOOR_UNUSED
at level.stages + 0*stage_size + stage.doors + 1*door_size + door.x,		db	DOOR_UNUSED
at level.stages + 0*stage_size + stage.doors + 2*door_size + door.y,		db	DOOR_UNUSED
at level.stages + 0*stage_size + stage.doors + 2*door_size + door.x,		db	DOOR_UNUSED
at level.stages + 0*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 0*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_BOUNCE
at level.stages + 0*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.shp_index,	db	1
at level.stages + 0*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_BOUNCE
at level.stages + 0*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.shp_index,	db	2
at level.stages + 0*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_BOUNCE
at level.stages + 0*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_UNUSED
; comp1
at level.stages + 1*stage_size + stage.item_type,	db	ITEM_SHIELD
at level.stages + 1*stage_size + stage.item_y,		db	10
at level.stages + 1*stage_size + stage.item_x,		db	70
at level.stages + 1*stage_size + stage.exit_l,		db	0
at level.stages + 1*stage_size + stage.exit_r,		db	2
at level.stages + 1*stage_size + stage.doors + 0*door_size + door.y,		db	DOOR_UNUSED
at level.stages + 1*stage_size + stage.doors + 0*door_size + door.x,		db	DOOR_UNUSED
at level.stages + 1*stage_size + stage.doors + 1*door_size + door.y,		db	DOOR_UNUSED
at level.stages + 1*stage_size + stage.doors + 1*door_size + door.x,		db	DOOR_UNUSED
at level.stages + 1*stage_size + stage.doors + 2*door_size + door.y,		db	DOOR_UNUSED
at level.stages + 1*stage_size + stage.doors + 2*door_size + door.x,		db	DOOR_UNUSED
at level.stages + 1*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 1*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_BOUNCE | ENEMY_BEHAVIOR_FAST
at level.stages + 1*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.shp_index,	db	1
at level.stages + 1*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_BOUNCE | ENEMY_BEHAVIOR_FAST
at level.stages + 1*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.shp_index,	db	2
at level.stages + 1*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_BOUNCE | ENEMY_BEHAVIOR_FAST
at level.stages + 1*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_UNUSED
; comp2
at level.stages + 2*stage_size + stage.item_type,	db	ITEM_LANTERN
at level.stages + 2*stage_size + stage.item_y,		db	2
at level.stages + 2*stage_size + stage.item_x,		db	166
at level.stages + 2*stage_size + stage.exit_l,		db	1
at level.stages + 2*stage_size + stage.exit_r,		db	EXIT_UNUSED
at level.stages + 2*stage_size + stage.doors + 0*door_size + door.y,		db	14
at level.stages + 2*stage_size + stage.doors + 0*door_size + door.x,		db	244
at level.stages + 2*stage_size + stage.doors + 0*door_size + door.target_level,	db	1
at level.stages + 2*stage_size + stage.doors + 0*door_size + door.target_stage,	db	2
at level.stages + 2*stage_size + stage.doors + 1*door_size + door.y,		db	DOOR_UNUSED
at level.stages + 2*stage_size + stage.doors + 1*door_size + door.x,		db	DOOR_UNUSED
at level.stages + 2*stage_size + stage.doors + 2*door_size + door.y,		db	DOOR_UNUSED
at level.stages + 2*stage_size + stage.doors + 2*door_size + door.x,		db	DOOR_UNUSED
at level.stages + 2*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.shp_index,	db	0
at level.stages + 2*stage_size + stage.enemies + 0*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_BOUNCE | ENEMY_BEHAVIOR_FAST
at level.stages + 2*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.shp_index,	db	1
at level.stages + 2*stage_size + stage.enemies + 1*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_BOUNCE | ENEMY_BEHAVIOR_FAST
at level.stages + 2*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.shp_index,	db	2
at level.stages + 2*stage_size + stage.enemies + 2*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_BOUNCE | ENEMY_BEHAVIOR_FAST
at level.stages + 2*stage_size + stage.enemies + 3*enemy_record_size + enemy_record.behavior,	db	ENEMY_BEHAVIOR_UNUSED
iend
resb 208-($-LEVEL_DATA_COMP)	; padding
